create database customerBehaviourDB;

USE customerBehaviourDB;

show tables;

select * from customers limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS total_revenue
FROM
    customers
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customers
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customers);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased AS product, 
    ROUND(AVG(review_rating), 2) as avg_rating
FROM
    customers
GROUP BY product
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM
    customers
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND((SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) * 100) / COUNT(*),
            2) AS discount_rate
FROM
    customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
WITH customer_type as (
	SELECT 
		CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END as customer_segment
	FROM
		customers)
SELECT 
    customer_segment, COUNT(1) AS customer_count
FROM
    customer_type
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?	
WITH item_rank as (
	SELECT 
		category, item_purchased, COUNT(customer_id) AS purchanse_count,
		ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as rnk
	FROM
		customers
	GROUP BY category , item_purchased)
SELECT 
    rnk, category, item_purchased, purchanse_count
FROM
    item_rank
WHERE
    rnk <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, 
    COUNT(customer_id) as customer_count
FROM
    customers
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT 
    *,
    ROUND(total_revenue * 100 / (SELECT 
                    SUM(purchase_amount)
                FROM
                    customers),
            2) AS contribution_percent
FROM
    (SELECT 
        age_group, SUM(purchase_amount) AS total_revenue
    FROM
        customers
    GROUP BY age_group
    ORDER BY total_revenue DESC) t;
